### ISSUE TITLE
How run the Qt?

### ISSUE THREAD

**Issue by feichai2004** [MarkMuth/QtKittiVisualizer#1]
I try to run ./qt-kitti-visualizer but it failed to load the .bin files? Where can I get the .bin files? On the KiTTi websites, the LIDAR files are saved in .xtx format.

**Comment by MarkMuth** [comment]
You need to download the .zip archives and the tracklets from 
http://www.cvlibs.net/datasets/kitti/raw_data.php just as mentioned in 
the README. I would be surprised if the format changed from the last 
time I used it.

Hope this could help you.
