### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by nitesh4146** [MarkMuth/QtKittiVisualizer#5]
I'm using Ubuntu 16.04 with qt5.2.1 and vtk6.3.0. I am getting the following error on cmake:

```
CMake Error at /usr/local/share/cmake-3.9/Modules/FindQt4.cmake:1318 (message):
  Found unsuitable Qt version "5.2.1" from
  /home/nitish/Qt5.2.1/5.2.1/gcc_64/bin/qmake, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:21 (find_package)
```
CMakeLists says that it supports QT5. Is there anything I'm missing here?

**Comment by MarkMuth** [comment]
Hi. Seems to me like your version of VTK was built using Qt4 which is why FindQt4.cmake is executed. I added some debug messages to the CMakeLists.txt, so that you can check the value of VTK_QT_VERSION after you run cmake.
